<?php 
$newPage = array( 
	'titleContent' => 'Intake Form',
	//'number' =>	2,
	'formCheckBoxesRadios' => 1,
	'formRepeater' => 1
);

$list['medicalConditions'] = array(
	"ADD/ADHD",
	"Alzheimer's Disease",
	"Anxiety",
	"Appettite",
	"Arthritis",
	"Osteoarthritis",
	"Psoriatic Arthritis",
	"Rheumatoid Arthritis",
	"Back and Neck Pain",
	"Bladder Pain",
	"Brain Injury",
	"Cancer Symptoms",
	"Chronic Pain",
	"Colitis",
	"Complex Regional Pain Syndrome",
	"Chrohn's Disease",
	"Denegerative Disc Disease",
	"Depression",
	"Eating Disorder",
	"Epilepsy",
	"Essential Tremors",
	"Fibromyalgia",
	"Gastrointestinal Disorders",
	"Glaucoma",
	"Head Injury",
	"Hepatitis HIV/AIDS",
	"Irritable Bowel Syndrome",
	"Jaw Pain",
	"Kidney Disease Libido",
	"Menopause",
	"Migraines",
	"Multiple Sclerosis",
	"Muscle Spasms",
	"Muscular Dystrophy",
	"Nausea",
	"Nerve Pain",
	"Parkinson's Disease",
	"Pelvic Pain",
	"Post operative Surgery Pain",
	"PMS/Menstrual Cramps",
	"PTSD",
	"Repetitive Strain",
	"Injury",
	"Seizures",
	"Sleep Disorders",
	"Spinal Cord Injury/Disease"
);